### PR TITLE
Using another api to count commits and update README.md

### LINKED ISSUE #12: refactor commits statistics algrithm for stackalytics
currently we use `stackalyticsDeviation` mechanism. but this is inherent incorrect. we should list commits on a repository ( https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository ) and filter them by user, date period, etc.

@xialonglee

### PR DESCRIPTION
**Pull request by xialonglee**
1. fix #12 
2. update README.mv that add dependecy specification `github.com/BurntSushi/toml`.
@bruceauyeung

### CODE REVIEW

File: githubstat/metrics_commit_request.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
+package githubstat
+
+import (
+	"fmt"
+	"github.com/google/go-github/github"
+	"strings"
+	"time"
+)
+
+type WarpRepositoryCommit struct {
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go]: `PullRequestCommit` is a better name , IMO.

File: githubstat/metrics_commit_request.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+	if !sameCommitter {
+		author = m.RepositoryCommit.Committer.Login
+	}
+	// TODO consider using template
+	query := *SHA + " repo:" + owner + "/" + repo + " type:pr" + " author:" + *author
+	pr := findPRfromCommit(client, query)
+	if pr == nil {
+		return false
+	}
+	m.MergedAt = pr.ClosedAt
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go:32]: i think `m.MergedAt` should  be assigned  `pr.MergedAt` , `pr.ClosedAt` is not identical to `pr.MergedAt`

File: githubstat/metrics_commit_request.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+	return true
+}
+
+func listCommits(client *github.Client, owner string, repo string, author string) ([]*github.RepositoryCommit, error) {
+	opt := &github.CommitsListOptions{
+		Author:      author,
+		ListOptions: github.ListOptions{PerPage: 100, Page: 1},
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go:40]: shouldn't list only page 1 commits, we can not assume user always have less than 100 commits per repository

File: githubstat/metrics_commit_request.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+	}
+
+	page := 1
+	var allCommits []*github.RepositoryCommit
+	for {
+		commits, resp, err := client.Repositories.ListCommits(owner, repo, opt)
+		if err != nil {
+			return nil, err
+		}
+
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go:50]: here we should filter out commits by merged time ( between stat begin time and stat end time ), by message pattern before we adding them into `allCommits`
note: stat begin time is included, but stat end time is excluded.

File: githubstat/metrics_commit_request.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+	opt := &github.CommitsListOptions{
+		Author:      author,
+		ListOptions: github.ListOptions{PerPage: 100, Page: 1},
+		//Head:        client.userName + ":",
+	}
+
+	page := 1
+	var allCommits []*github.RepositoryCommit
+	for {
+		commits, resp, err := client.Repositories.ListCommits(owner, repo, opt)
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go:46]: it would be better if we consider filter out commits by `CommitsListOptions.Since` and `CommitsListOptions.Until`. for example, commits committed after `CommitsListOptions.Until` is absoultely merged after `CommitsListOptions.Until`

File: githubstat/metrics_commit_request.go [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+			// 100 is so big, it should not return so much results
+			// so no need to handle the "NextPage" attr of the response.
+		},
+	}
+	results, _, err := client.Search.Issues(query, opt)
+	if err != nil {
+		fmt.Printf("error: %v\n", err)
+		return nil
+	} else if *results.Total > 1 {
+		fmt.Printf("warning: find multiple pull requests from a commit's SHA, we take the first one.\n")
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go:92]: why we can find more than one pull requests from commit SHA?

File: githubstat/metrics_commit_request.go [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+	fmt.Printf("%s/%s : listing commits of stackalytics.com style\n", owner, repo)
+	overallCommits, err := listCommits(client, owner, repo, author)
+	if err != nil {
+		panic(err)
+	}
+	overallCommits = filterCommits(overallCommits)
+
+	var warpOverallCommits []*WarpRepositoryCommit
+	for _, commit := range overallCommits {
+		warpCommit := &WarpRepositoryCommit{commit, owner, repo, &time.Time{}}
```
Comment (bruceauyeung) [inline githubstat/metrics_commit_request.go]: this is no need to pass in a reference to zero time, `nil` is enough

**Review by bruceauyeung — CHANGES_REQUESTED** [review]
thanks for your PR!

File: githubstat/metrics_commit_request.go (hunk 2 above)
Comment (xialonglee) [reply githubstat/metrics_commit_request.go:32]: because there is no `MergeAt` attr, only `ClosedAt`, `CreatedAt` and `UpdateAt` attributes in the issue(pull request) struct, `ClosedAt` is the closest time stamp to the merge time

File: githubstat/metrics_commit_request.go (hunk 3 above)
Comment (xialonglee) [reply githubstat/metrics_commit_request.go:40]: pages was handled in the line 53 to 57.

**Comment by xialonglee** [comment]
1. `WarpRepositoryCommit` was refactored to `PullRequestCommit`
2. Only ClosedAt, CreatedAt and UpdateAt attributes in the issue(pull request) struct, ClosedAt is the closest time stamp to the pr merge time.
3. pages was handled in the line 53 to 57 in the function `listCommits`
4. stat end time is assigned to the `Until` attr of `github.CommitsListOptions`
5. `SHA` problem was clear in the online discussion.
6. TODO need to filter out prs which merged before stat start time

File: githubstat/metrics_commit_request.go (hunk 2 above)
Comment (bruceauyeung) [reply githubstat/metrics_commit_request.go:32]: @xialonglee you should try to convert `Issue` to `PullRequest`
